### PR TITLE
Telegram stickers

### PR DESCRIPTION
**Pull request by kvangent**
@drewreece Test this out and see if you can find any issues. If you can't, accept it and then I'll accept your PR on the master branch. This way you can still receive credit since you did most of the work. 

If I don't hear anything from you in 24 hours, I will just merge it myself.

### CODE REVIEW

**Comment by drewreece** [comment]
@kvangent, thanks for working on it.

I pulled from your telegram_stickers branch & got this error…

`
  File "/home/pi/PokeAlarm/alarms/Telegram/telegram_alarm.py", line 28
    'body': "<gmaps> \n Lure will expire at <24h_time> (<time_left>).",
          ^
SyntaxError: invalid syntax

`

There are 2 copies of the body for some reason & a missing comma? I added a comma after the first one & deleted the second copy but then it fails with…

`
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in **import**
    result = _import(_args, *_kwargs)
  File "/home/pi/PokeAlarm/alarms/Telegram/telegram_alarm.py", line 29
    },
    ^
SyntaxError: invalid syntax

`

The line with `'sticker_id':` has no value?
I set it to 'None' to get it to work. 

Then it fails with…

`
  File "/home/pi/PokeAlarm/alarms/Telegram/telegram_alarm.py", line 120
    elif:
        ^
SyntaxError: invalid syntax
`
So I changed that to an `else:` along with line 128 and 135 (they all have empty 'elif:'s)

After all that it runs but notifications fail with this log output.…

2016-09-27 23:55:07,767 [     alarm_manager] [   INFO] Eevee notication was triggered!
2016-09-27 23:55:07,773 [     alarm_manager] [  ERROR] Error while processing request: global name 'alert' is not defined

Sorry if this does not help, it looks like it's broken to me. I also moved to a new directory, did a new clone as follows & retested with the same results so I don't think I botched the pull

`git clone -b telegram_stickers https://github.com/kvangent/PokeAlarm.git`

Am I doing something wrong? It's entirely possible my config is incorrect, but I'm having a tough time keeping up with the changes. Any ideas where to look for the 'global name 'alert' is not defined' issue?

**Comment by kvangent** [comment]
@drewreece The only thing you did wrong was trust my code! I forgot to push a commit. If you try again it should be much easier this time.

**Comment by drewreece** [comment]
Hehe, that works now :) 
It's very early here (or very late) so I'm not seeing any gym changes or lured stops, I'll have to check that in a few hours. I am getting stickers, text & maps for the mons in Telegram, it seems correct.

Do you want larger copies of the stop & gym icons I made for the stickers? 

EDIT: Do I need to merge your work? I don't know what needs to be done, I'm just happy to get it into the main project.

**Comment by kvangent** [comment]
@drewreece You need to accept my Pull Request into your branch. Then I can accept this PR into the master branch.

I'm not worried about the icons, but if you have icons for each of the teams, it would be nice to get those made as stickers.

**Comment by kvangent** [comment]
@drewreece Are we ready to pull this?

**Comment by drewreece** [comment]
Here are new stickers ID's for the gyms…
BQADBAADHwADjGt_DWwRwTlwYq71Ag :grey (updated version)
BQADBAADHQADjGt_DWh6bmUsF_GeAg :blue-mystic
BQADBAADGwADjGt_DcVn_7MprUVwAg :yellow-instinct 
BQADBAADGQADjGt_DbsN-MC0jtwKAg :red-valor

They look like…
gym-grey256
gym-blue256
gym-red256
gym-yellow256

@kvangent, can you add these please?

**Comment by kvangent** [comment]
@drewreece I have added them. They look great.

I apologize Github isn't give you credit like I thought it would - but let me know what your discord username is and I'll make sure you get a contributor tag.

**Comment by drewreece** [comment]
Excellent, they seem to be working fine :)

Don't worry about the credit, I haven't created a Discord account & don't think I can keep up with the chatter there.

**Pull request merged**
